config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views import defaults as default_views
from drf_spectacular.views import SpectacularAPIView, SpectacularSwaggerView
from rest_framework.authtoken.views import obtain_auth_token

urlpatterns = [
    path("", include("zurjong.core.urls")),
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    path("users/", include("zurjong.users.urls", namespace="users")),
    path("teachers/", include("zurjong.teachers.urls", namespace="teachers")),
    path("accounts/", include("allauth.urls")),
    # Your stuff: custom urls includes go here
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# API URLS
urlpatterns += [
    # API base url
    path("api/", include("config.api_router")),
    # DRF auth token
    path("auth-token/", obtain_auth_token),
    path("api/schema/", SpectacularAPIView.as_view(), name="api-schema"),
    path(
        "api/docs/",
        SpectacularSwaggerView.as_view(url_name="api-schema"),
        name="api-docs",
    ),
]

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

zurjong/core/urls.py
from django.urls import path
from django.views.generic import TemplateView

from .views import home_view

app_name = "core"
urlpatterns = [
    path("", home_view, name="home"),
    path(
        "about/", TemplateView.as_view(template_name="pages/about.html"), name="about"
    ),
    path(
        "contact/", TemplateView.as_view(template_name="pages/contact.html"), name="contact"
    ),
    path(
        "tibetan/", TemplateView.as_view(template_name="pages/tibetan-section.html"), name="tibetan-section"
    ),
    path(
        "terms-and-conditions/", TemplateView.as_view(template_name="pages/terms_and_conditions.html"), name="terms_and_conditions"
    ),
]

zurjong/teachers/urls.py
from django.urls import path

from .views import tutor_list_view, update_profile

app_name = "teachers"
urlpatterns = [
    path("", view=tutor_list_view, name="list"),
    path("~update/", view=update_profile, name="update_profile"),
]

zurjong/users/urls.py
from django.urls import path

from zurjong.users.views import (
    student_signup,
    teacher_signup,
    user_detail_view,
    user_redirect_view,
    user_update_view,
)

app_name = "users"
urlpatterns = [
    path("~redirect/", view=user_redirect_view, name="redirect"),
    path("~update/", view=user_update_view, name="update"),
    path("<str:username>/", view=user_detail_view, name="detail"),
    path("signup/teacher/", view=teacher_signup, name="signup_teacher"),
    path("signup/student/", view=student_signup, name="signup_student"),
]

zurjong/core/models.py
from django.db import models

# Create your models here.

zurjong/students/models.py
from ast import Sub
from email.policy import default

from django.core.validators import MaxValueValidator, MinValueValidator
from django.db import models

from zurjong.teachers.models import StudentAgeRange
from zurjong.users.models import Student


class Subjects(models.Model):
    name = models.CharField(max_length=100)

class StudentProfile(models.Model):

    TIME_AM_OR_PM = (
        ("AM", "AM"),
        ("PM", "PM")
    )

    user = models.OneToOneField(Student, on_delete=models.CASCADE)
    age_range = models.ManyToManyField(StudentAgeRange)
    learning_hour_per_week = models.IntegerField()
    want_to_learn = models.ManyToManyField(Subjects)
    lang_barrier = models.BooleanField(default=False)

    # tuition timing
    tuition_start_time = models.IntegerField(
        validators=[MinValueValidator(1), MaxValueValidator(12)]
    )
    tuition_end_time = models.IntegerField(
        validators=[MinValueValidator(1), MaxValueValidator(12)]
    )
    am_or_pm = models.CharField(max_length=2, choices=TIME_AM_OR_PM, default="PM")

    def __str__(self):
        return f"{self.user.username}"

zurjong/teachers/models.py
from django.db import models
from django.dispatch import receiver
from django.utils.translation import gettext_lazy as _
from tinymce.models import HTMLField

from zurjong.users.models import Teacher, User


class StudentAgeRange(models.Model):
    name = models.CharField(max_length=20)
    low = models.IntegerField()
    high = models.IntegerField()

    def __str__(self):
        return f"{self.name} ({self.low}-{self.high}) years"


class Curriculum(models.Model):

    class Subjects(models.TextChoices):
        MATH = 'MATH', _('Math')
        SCIENCE = 'SCIENCE', _('Science')
        TIBETAN = 'TIBETAN', _('Tibetan')
        CODING = 'CODING', _('Coding')

    name = models.CharField(max_length=100)
    url = models.URLField()
    subject = models.CharField(max_length=20, choices=Subjects.choices)

    def __str__(self):
        return self.name

class Language(models.Model):
    name = models.CharField(max_length=20)

    def __str__(self):
        return self.name

class TeacherProfile(models.Model):

    user = models.OneToOneField(Teacher, on_delete=models.CASCADE, related_name="profile", primary_key=True)
    contact_number = models.CharField(max_length=13, null=True, blank=True)
    bio = HTMLField(null=True, blank=True)
    qualification = HTMLField(null=True, blank=True)
    languages = models.ManyToManyField(Language, blank=True)
    students = models.ManyToManyField(StudentAgeRange, blank=True)
    curriculums = models.ManyToManyField(Curriculum, blank=True)
    fee_per_hour = models.IntegerField(_("Fee per Hour in $ USD"), default=0, null=True, blank=True)

    def __str__(self):
        return f"{self.user.name}"

@receiver(models.signals.post_save, sender=User)
def create_teacher_profile(sender, instance, created, **kwargs):
    if created and instance.type == User.Types.TEACHER:
        TeacherProfile.objects.create(user=instance)

zurjong/users/models.py
from django.contrib.auth.models import AbstractUser, UserManager
from django.db import models
from django.db.models import CharField
from django.urls import reverse
from django.utils.translation import gettext_lazy as _


class User(AbstractUser):
    """
    Default custom user model for Zurjong.
    If adding fields that need to be filled at user signup,
    check forms.SignupForm and forms.SocialSignupForms accordingly.
    """

    class Types(models.TextChoices):
        TEACHER = 'T', _('Teacher')
        STUDENT = 'S', _('Student')

    name = CharField(_("Full Name"), blank=True, max_length=255)
    type = models.CharField(max_length=1, choices=Types.choices, default=Types.TEACHER)

    def get_absolute_url(self):
        """Get url for user's detail view.

        Returns:
            str: URL for user detail.

        """
        return reverse("users:detail", kwargs={"username": self.username})

class TeacherManager(UserManager):
    def get_queryset(self, *args, **kwargs):
        return super().get_queryset(*args, **kwargs).filter(type=User.Types.TEACHER)

class Teacher(User):
    objects = TeacherManager()

    class Meta:
        proxy = True

    def save(self, *args, **kwargs):
        if not self.pk:
            self.type = User.Types.TEACHER
        return super().save(*args, **kwargs)

class StudentManager(UserManager):
    def get_queryset(self, *args, **kwargs):
        return super().get_queryset(*args, **kwargs).filter(type=User.Types.STUDENT)

class Student(User):
    objects = StudentManager()

    class Meta:
        proxy = True

    def save(self, *args, **kwargs):
        if not self.pk:
            self.type = User.Types.STUDENT
        return super().save(*args, **kwargs)

zurjong/teachers/forms.py
from django import forms

from .models import TeacherProfile


class TeacherProfileUpdateForm(forms.ModelForm):
    class Meta:
        model = TeacherProfile
        fields = ("contact_number", "bio", "qualification", "languages", "students", "curriculums", "fee_per_hour", )
        widgets = {
            "languages": forms.CheckboxSelectMultiple(),
            "students": forms.CheckboxSelectMultiple(),
            "curriculums": forms.CheckboxSelectMultiple(),
        }

zurjong/users/forms.py
from allauth.account.forms import SignupForm
from allauth.socialaccount.forms import SignupForm as SocialSignupForm
from django import forms
from django.contrib.auth import forms as admin_forms
from django.contrib.auth import get_user_model
from django.utils.translation import gettext_lazy as _

from .models import Teacher

User = get_user_model()


class UserAdminChangeForm(admin_forms.UserChangeForm):
    class Meta(admin_forms.UserChangeForm.Meta):
        model = User


class UserAdminCreationForm(admin_forms.UserCreationForm):
    """
    Form for User Creation in the Admin Area.
    To change user signup, see UserSignupForm and UserSocialSignupForm.
    """

    class Meta(admin_forms.UserCreationForm.Meta):
        model = User

        error_messages = {
            "username": {"unique": _("This username has already been taken.")}
        }


class UserSignupForm(SignupForm):
    """
    Form that will be rendered on a user sign up section/screen.
    Default fields will be added automatically.
    Check UserSocialSignupForm for accounts created from social.
    """

class UserSocialSignupForm(SocialSignupForm):
    """
    Renders the form when user has signed up using social accounts.
    Default fields will be added automatically.
    See UserSignupForm otherwise.
    """

class TeacherSignupForm(SignupForm):
    """
    Form that will be rendered on a Teacher sign up section/screen.
    """

    def save(self, request):
        user = super().save(request)
        user.type = User.Types.TEACHER
        user.save()
        return user

class TeacherUpdateForm(forms.ModelForm):
    class Meta:
        model = Teacher
        fields = ["name"]

class StudentSignupForm(SignupForm):
    """
    Form that will be rendered on a Teacher sign up section/screen.
    """

    def save(self, request):
        user = super().save(request)
        user.type = User.Types.STUDENT
        user.save()
        return user

zurjong/core/views.py
from typing import Any, Dict

from django.views.generic import TemplateView

from zurjong.users.models import Teacher


class HomeView(TemplateView):
    template_name = "pages/home.html"

    def get_context_data(self, **kwargs: Any) -> Dict[str, Any]:
        context = super().get_context_data(**kwargs)
        teacher_samples = Teacher.objects.order_by("?")[:10]
        context["teachers"] = teacher_samples
        return context

home_view = HomeView.as_view()

zurjong/students/views.py
from django.shortcuts import render

# Create your views here.

zurjong/teachers/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.shortcuts import redirect, render
from django.views.generic import ListView

from zurjong.users.forms import TeacherUpdateForm
from zurjong.users.models import Teacher

from .forms import TeacherProfileUpdateForm


@login_required
def update_profile(request):
    if request.method == "POST":
        teacher_form = TeacherUpdateForm(request.POST, instance=request.user)
        teacher_profile_form = TeacherProfileUpdateForm(request.POST, instance=request.user.profile)

        if teacher_form.is_valid() and teacher_profile_form.is_valid():
            teacher_form.save()
            teacher_profile_form.save()
            messages.success(request, "Your profile was successfully updated!")
            return redirect("users:detail", request.user.username)
    else:
        teacher_form = TeacherUpdateForm(instance=request.user)
        teacher_profile_form = TeacherProfileUpdateForm(instance=request.user.profile)

    context = {
        "teacher_form": teacher_form,
        "teacher_profile_form": teacher_profile_form,
    }

    return render(request, "teachers/profile_update.html", context)


class TutorListView(ListView):
    models = Teacher
    queryset = Teacher.objects.all()
    template_name = "teachers/tutors.html"
    context_object_name = "teachers"

tutor_list_view = TutorListView.as_view()

zurjong/users/api/views.py
from django.contrib.auth import get_user_model
from rest_framework import status
from rest_framework.decorators import action
from rest_framework.mixins import ListModelMixin, RetrieveModelMixin, UpdateModelMixin
from rest_framework.response import Response
from rest_framework.viewsets import GenericViewSet

from .serializers import UserSerializer

User = get_user_model()


class UserViewSet(RetrieveModelMixin, ListModelMixin, UpdateModelMixin, GenericViewSet):
    serializer_class = UserSerializer
    queryset = User.objects.all()
    lookup_field = "username"

    def get_queryset(self, *args, **kwargs):
        assert isinstance(self.request.user.id, int)
        return self.queryset.filter(id=self.request.user.id)

    @action(detail=False)
    def me(self, request):
        serializer = UserSerializer(request.user, context={"request": request})
        return Response(status=status.HTTP_200_OK, data=serializer.data)

zurjong/users/views.py
from typing import Any, List, Optional

from allauth.account.views import SignupView
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse
from django.utils.translation import gettext_lazy as _
from django.views.generic import DetailView, RedirectView, UpdateView

from .forms import StudentSignupForm, TeacherSignupForm

User = get_user_model()


class UserDetailView(LoginRequiredMixin, DetailView):

    model = User
    slug_field = "username"
    slug_url_kwarg = "username"

    def get_template_names(self) -> List[str]:
        if self.request.user.type == User.Types.TEACHER:
            return "teachers/profile.html"
        elif self.request.user.type == User.Types.STUDENT:
            return "students/profile.html"
        else:
            super().get_template_names()

    def get_context_object_name(self, obj: Any) -> Optional[str]:
        if self.request.user.type == User.Types.TEACHER:
            return "teacher"
        elif self.request.user.type == User.Types.STUDENT:
            return "student"
        else:
            super().get_context_object_name(obj)



user_detail_view = UserDetailView.as_view()


class UserUpdateView(LoginRequiredMixin, SuccessMessageMixin, UpdateView):

    model = User
    fields = ["name"]
    success_message = _("Information successfully updated")

    def get_success_url(self):
        assert (
            self.request.user.is_authenticated
        )  # for mypy to know that the user is authenticated
        return self.request.user.get_absolute_url()

    def get_object(self):
        return self.request.user


user_update_view = UserUpdateView.as_view()


class UserRedirectView(LoginRequiredMixin, RedirectView):

    permanent = False

    def get_redirect_url(self):
        if self.request.user.type == User.Types.TEACHER:
            if not self.request.user.profile.bio:
                return reverse("teachers:update_profile")
        return reverse("users:detail", kwargs={"username": self.request.user.username})


user_redirect_view = UserRedirectView.as_view()


class TeacherSignupView(SignupView):
    form_class = TeacherSignupForm

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["user_type"] = "Teacher"
        return context

teacher_signup = TeacherSignupView.as_view()

class StudentSignupView(SignupView):
    form_class = StudentSignupForm

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["user_type"] = "Student"
        return context

student_signup = StudentSignupView.as_view()

zurjong/templates/base.html
{% load static i18n %}<!DOCTYPE html>
{% get_current_language as LANGUAGE_CODE %}
<html lang="{{ LANGUAGE_CODE }}">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>Zurjong | {% block title %}{% endblock title %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="Behold My Awesome Project!">
    <meta name="author" content="Tenzin">

    <link rel="icon" href="{% static 'images/favicons/favicon.ico' %}">

    {% block css %}
    <!-- Latest compiled and minified Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.1.3/css/bootstrap.min.css" integrity="sha512-GQGU0fMMi238uA+a/bdWJfpUGKUkBdgfFdgBm72SUQ6BeyWjoY/ton0tEjH+OSH9iP4Dfh+7HM0I9f5eR0L/4w==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <!-- Your stuff: Third-party CSS libraries go here -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.2/font/bootstrap-icons.css">

    <!-- This file stores project-specific CSS -->
    <link href="{% static 'css/project.css' %}" rel="stylesheet">
    {% endblock %}
    <!-- Le javascript
    ================================================== -->
    {# Placed at the top of the document so pages load faster with defer #}
    {% block javascript %}
      <!-- Bootstrap JS -->
      <script defer src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.1.3/js/bootstrap.min.js" integrity="sha512-OvBgP9A2JBgiRad/mM36mkzXSXaJE9BEIENnVEmeZdITvwT09xnxLtT4twkCa8m/loMbPHsvPl0T8lRGVBwjlQ==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
      <!-- Your stuff: Third-party javascript libraries go here -->

      <!-- place project specific Javascript in this file -->
      <script defer src="{% static 'js/project.js' %}"></script>

    {% endblock javascript %}

  </head>

  <body>

    <div class="mb-1">
      <nav class="navbar navbar-expand-md navbar-light bg-light">
        <div class="container">
          <button class="navbar-toggler navbar-toggler-right" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <a class="navbar-brand text-primary" href="{% url 'core:home' %}">Zurjong</a>

          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav ms-auto">
              <li class="nav-item">
                <a class="nav-link" href="{% url 'core:about' %}">About Us</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'core:contact' %}">Contact</a>
              </li>
              <li class="nav-item active">
                <a class="nav-link" href="{% url 'core:tibetan-section' %}">བོད་ཡིག</a>
              </li>
            </ul>
            <div class="ms-auto">
              {% if request.user.is_authenticated %}
                {# URL provided by django-allauth/account/urls.py #}
                <a class="navbar-link" href="{% url 'users:detail' request.user.username  %}">{% translate "Profile" %}</a>
                {# URL provided by django-allauth/account/urls.py #}
                <a class="ms-2 navbar-btn btn btn-sm btn-outline-secondary" href="{% url 'account_logout' %}">{% translate "Sign Out" %}</a>
              {% else %}
                {# URL provided by django-allauth/account/urls.py #}
                <a class="navbar-btn btn btn-sm btn-primary" href="{% url 'account_login' %}">{% translate "Sign In" %}</a>
              {% endif %}
            </div>
          </div>
        </div>
      </nav>

    </div>

      {% block landing_page %}
      {% endblock landing_page %}

      <div class="container">
        {% if messages %}
          {% for message in messages %}
            <div class="alert alert-dismissible {% if message.tags %}alert-{{ message.tags }}{% endif %}">
              {{ message }}
              <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
          {% endfor %}
        {% endif %}


        {% block content %}
        {% endblock content %}
      </div> <!-- /container -->
    </div>

    {% block modal %}{% endblock modal %}

    {% block inline_javascript %}
    {% comment %}
    Script tags with only code, no src (defer by default). To run
    with a "defer" so that you run inline code:
    <script>
      window.addEventListener('DOMContentLoaded', () => {/* Run whatever you want */});
    </script>
    {% endcomment %}
    {% endblock inline_javascript %}
  </body>
</html>